version: '3'

services:

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - fullcycle
    depends_on:
      - backend 

  backend:
    build: 
      context: ./backend 
    container_name: backend
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    restart: always
    networks:
      - fullcycle
    command: npm start  
    working_dir: /usr/src/app
    depends_on:
      - db 

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle
networks:
  fullcycle:
    driver: bridge